### ISSUE TITLE
Move to "Address or Zip Code" Entry

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#105]
We've received a bunch of reports that niether zip code nor GPS provide 100% functionality with respect to congressional districts.  We need to allow passing a full address to the API in these cases.

- Remove zip code validation
- make text field read "Enter Zip or Address"
- update any references to zip code (we can just call this an "address" in the code)
- URL encode whatever they type and pass to API in `FetchIssuesOperation`
- update any alert dialog messaging about split districts to reflect this

**Comment by subdigital** [comment]
@tomburns is working on this.

**Comment by tomburns** [comment]
Welp, just noticed this :) I'll update the UI text in my PR

**Comment by tomburns** [comment]
@subdigital I think this issue can be closed after PR #106
