### ISSUE TITLE
Reporting outcome of a call

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#12]
HTTP POST to `/report` including

- result (must be one of `'unavailable'`, `'vm'`, `'contacted'`)
- contact id
- issue id

Then save to local persistence (a plist, or maybe [Pantry](https://github.com/nickoneill/Pantry)? 😄 ) the outcome of this issue.

Issues that have a saved result show up w/ a green checkmark on the issues list.  This can be done in `IssuesViewController` by setting the `isChecked` flag on `IssueCell`.

**Comment by mccarron** [comment]
Going to integrate this into the Script Detail screen.

**Comment by mccarron** [comment]
I also see `location` and `phone` on the backend call, should we also send that?https://github.com/5calls/5calls/blob/241e06aee6d56f0ffe8495043578ae003e35b222/go/report.go#L25

**Comment by mccarron** [comment]
Apparently we need to support logging calls to the reps more than once. So reopening the issue.

**Comment by mccarron** [comment]
Also add support for the 'phone' parameter, which we can capture based on what call button was pressed.
