### ISSUE TITLE
Gracefully handle office locations w/ no names

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#121]
Sometimes the office names aren't present in the API response for the House.  Just need to check for this so we don't see something like:  `"222-333-4567 ()"`

**Comment by bengottlieb** [comment]
Do we have any examples?

**Comment by subdigital** [comment]
It's dependent on the data, but try to find an issue with a house representative.  I found one w/ zip 77429 and I posted the picture to slack.

**Comment by bengottlieb** [comment]
Hmm, every issue I'm seeing is either Senate- or Governor-only, or just hits a House subcommittee.

**Comment by mccarron** [comment]
Fixed by #122
