### ISSUE TITLE
Move add reminder to home screen

### ISSUE THREAD

**Issue by mergesort** [5calls/ios#126]
We have some users writing in asking for a reminders feature, which makes me think that it's not prominent enough.

My suggestion is to add a button on the home screen, in the top left corner of the header.
Design-wise I was thinking a bell icon, which is either outlined or full, depending on whether the user has set them up or not. Tapping it would take you to the same screen as it currently does.

**Comment by chrisbrandow** [comment]
I made a simple implementation with a button in the top left corner as suggested.
