### ISSUE TITLE
Request: use a more neutral status bar color, since red is similar to the "recording" state

### ISSUE THREAD

**Issue by bgerstle** [5calls/ios#131]
When using the microphone or recording, there's a red bar across the top of the device. It doesn't look exactly like 5calls does, but nonetheless it gives the (false) impression the app is using my microphone for something.

I realize it's probably a "red, white, and blue" color scheme thing, but figured I'd write let you guys know about the other cases when a red bar shows up all the same. 

Otherwise great work on the app! Hope I can make a contribution at some point.

**Comment by subdigital** [comment]
Agree with this.  I'm not sure exactly what to do about it, but it does conflict with the recording status bar.

Off the top of my head, choices are:

- remove the red status bar entirely
- use standard white status bar w/ red nav bar (ugh)
- maybe use blue everywhere instead?

@mattbischoff any suggestions here?

**Comment by mattbischoff** [comment]
I was thinking about this this morning actually! Right now I think the brightness/contrast of the status bar detracts from what we’d want people to be paying attention to. I think we should remove the background entirely and make the status bar style `default`. If we want to keep the red accent color in the app, we can probably find another suitable place for it.

**Comment by subdigital** [comment]
Maybe just a thin red line instead of a solid red?  Otherwise 👍

**Comment by subdigital** [comment]
Standard nav bar is back.  Looks good.
