### ISSUE TITLE
As a user, I can get push notifications when my friends make a call...

### ISSUE THREAD

**Issue by bgerstle** [5calls/ios#132]
...so that I can be motivated to make more calls!

Haven't thought further about the cross-platform implications here, but if there's a way to try it as an experiment, I think it would be awesome!

**Comment by subdigital** [comment]
Push notifications are being discussed, but probably won't be exactly as you describe.

We have no notion of friends, nor do we want to track and user identifiable information on the server.  Push will probably come in a form of an important issue that we can blast out to folks.

Location is also part of the equation.  Like for instance they know that a certain senator is for a piece of dangerous legislation, they could target those constituents directly.

**Comment by nickoneill** [comment]
Thanks @bgerstle! This is a great idea, social pressure from friends can be very motivating and this would definitely drive people back to see the issues.

Requirements would be some sort of social-connection signup which has already been discussed as something we should do.

**Comment by nickoneill** [comment]
that's what I get for commenting on tabs that are 3 days old

**Comment by subdigital** [comment]
Well if it's up for discussion still I'm happy to open it back up.

**Comment by nickoneill** [comment]
Your point is absolutely the direction we're headed in for the near future. Some sort of account login would be a ways down the road still. Let's focus on the account-less notifications for the moment and we can revisit in the future.
