### ISSUE TITLE
Use consistent color to indicate "Completed" status

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#142]
Currently we use green checkmarks to indicate _complete_ in the table view cells for issues and contacts, but a solid blue fill for the result buttons.

It was suggested to use the same color for both, linking the meaning of a completed action from the button -> contact -> issue.

![](https://www.dropbox.com/s/n1syh8x9hrnb9pu/Screenshot%202017-03-29%2010.41.58.png?dl=1)

In addition to the above, I'd like to have an indication of partial completeness for issues. If you've contact 1 out of 3 contacts for an issue, I think maybe the empty circle with a dot in it, something like this:

![](https://www.dropbox.com/s/1b2oh0qq7kttkpt/Screenshot%202017-03-29%2010.47.12.png?dl=1)

**Comment by Abizern** [comment]
Image links seem to be broken. :(

**Comment by nickoneill** [comment]
This may be moot considering some recent visual changes in https://github.com/5calls/ios/pull/166, checkin with @ianyh here

**Comment by ianyh** [comment]
What I had mocked up generally moved towards using blue for indicating completion, both the marker in the list and the buttons to set results. Green would be reserved for the actual call action. It doesn't have a sense of partial completion, though, which is kind of compelling.
