### ISSUE TITLE
Should inform user sooner that address is ambiguous 

### ISSUE THREAD

**Issue by dempseyatgithub** [5calls/ios#158]
As a new user, traveling when I downloaded the app, I entered my zip code as my location.

This was ambiguous as to my representative. So in many issues, only Senators appeared. I had to find an issue only for the House to see a warning that my address info was not specific enough to identify my Representative.

It would be great if that warning appeared right when you enter your address.

**Comment by subdigital** [comment]
Sorry for the late response on this. This feature does exist, however it only prompted you if you changed your location from the issue detail screen. There are 2 places you can set your location from and the handling of this action is duplicated, so I need to revisit this design. A few things are in flux right now that will affect this so I will make sure this gets implemented as part of this work.

Thanks for reporting!
