### ISSUE TITLE
Refresh issues list periodically

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#159]
Some (probably less-tech savvy) people email us and say that the issues list doesn't refresh day-to-day. I suspect this is older users who infrequently use their device (sometimes iPads) so the app isn't getting killed between launches, leading to out-of-date issues.

Two things we could do here:
* Provide automatic refresh when the app is foregrounded if the issues haven't been refreshed in ~12 hours
* Pull-to-refresh control on the issues list for manually checking for new issues

**Comment by mccarron** [comment]
Closed by #163
