### ISSUE TITLE
Add option to copy phone number for pasting into Skype, etc

### ISSUE THREAD

**Issue by ericallam** [5calls/ios#162]
Another one that would be really useful for expats: adding Skype as a call option. Skype is able to call US mobile/landlines (as long as your Skype account has a phone number and Skype credit) and is usually much cheaper than just calling to the US through the cell carrier.

**Comment by nickoneill** [comment]
That sounds like a good first step rather than thinking about specific support for various calling apps @lazerwalker - let me know if you have any questions if you start a PR.

**Comment by nickoneill** [comment]
A request to copy phone numbers was made again

**Comment by cselin** [comment]
I can take care of this

**Comment by heathermh** [comment]
> I can take care of this

Hey @cselin I was just looking at making a tappable link to initiate call, especially for users with VoiceOver. What do you think about enabling both options? Suggestions for design?

**Comment by cselin** [comment]
@heathermh, yes it looks like the calling functionality wasn't brought over to the SwiftUI redesign. I've gotten something working for the main number (tap to call, long tap to copy), but it doesn't seem to work for list items out of the box. I'm considering having a tap on either bring up a bottom sheet with those two options, but then I think it'll then show a second sheet for calling, which isn't ideal. I'm going to spend a little more time on the tap/long tap option unless you have some other ideas?

**Comment by heathermh** [comment]
@cselin I think we could figure out a way to make VoiceOver work or set up alt behavior if it's tap to call, long tap to copy.

If that won't work within the existing menu, it's probably not all bad to have a sheet that lists the other numbers, with options to call or copy.

**Comment by cselin** [comment]
Here's an example where I'm using a `confirmationDialog` for both the main number and field offices. It should be accessible out of the box, but I don't love the double confirmation for calling 😕
https://github.com/5calls/ios/assets/810263/bc4735d2-6340-42af-8439-366ffba706a0

I'm thinking maybe something closer to my original idea with tap to call and tap to hold to copy the main number (not super discoverable, but is a common paradigm) and seeing if I can add a tappable copy icon next to the field office items.

**Comment by cselin** [comment]
I was able to get something decent using `ControlGroup` within the `Menu`, but then the section label goes away. I think this may be the best direction if I can display the field office somehow...
![IMG_2379](https://github.com/5calls/ios/assets/810263/a58d0da4-62be-4711-a5bf-265deb319640)

**Comment by nickoneill** [comment]
Tappable copy in the menu looks nice, the section names are important to distinguish them though. Worst case scenario we could move this to a custom modal if the menu is too inflexible?

I do prefer the single-tap-to-call over the extra call/copy prompt. Could the main line be listed in the menu with a copy option at the top if long-press-to-copy doesn't work?
