### ISSUE TITLE
Implement native review prompt

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#173]
We should ask the user to leave us a review using the native review prompt after the user has completed x number of calls

**Comment by Abizern** [comment]
Maybe even after X number of calls on Y separate days?

**Comment by nickoneill** [comment]
I'm not sure the days component is required - there is a contingent that likes to make all the calls but I suspect the much more common situation is returning to the app when a user sees another mention on twitter for another issue they care about.

Are you interested in implementing this @Abizern?

**Comment by Abizern** [comment]
Sure, I'll give it a shot.

Questions:
- What value of x should we go for?
- Is there a restriction on when the review request is made? for example, if the user has just completed one call and is going on to the next, is that a good time to pop up an alert?
- Is there tracking in the app, if so, how do we want to track this?

**Comment by nickoneill** [comment]
Awesome! Send me an email if you want an invite to our slack as well - participating on github is fine, I understand all too well if yet another slack is just another distraction.

* Let's say 5 completed calls (i.e. they've reached the end of the list of contacts five times, doesn't matter if those contacts were contacted, voicemail, skipped, etc)
* We don't have a great UX flow for finishing a group of contacts, rather than navigating to the next call it just shows a checkmark. So this is an OK place to interrupt with an alert
* There are fabric events, would be great to create a custom event to see how frequently this appears, don't worry about tracking the result though
