### ISSUE TITLE
Group by category on the more issues page

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#174]
We already send category names along with the issues on "more issues", these should be organized by their category with a nice little header.

(may want to consider using the new `all=true` query param which fetches all issues at once rather than active, then inactive later)

**Comment by indraShan** [comment]
@nickoneill 
First timer, so may be a stupid question. If I understand the issue correctly: on 'more issues' screen (after tapping 'more issues' cell from Home) we want to group issues by their category, is this correct? But on Home we don't want any changes (i.e. continue showing all issues together like the app does now).

Currently category is not even parsed by the app (it is being sent by the server though.) So to close this bug: Make changes to the Issue struct to parse and save category of the issue. Then make UI changes to add a 'header' cell for every section (sections will be created based on how many unique categories we have received in the response). Is my understanding correct?

**Comment by nickoneill** [comment]
Exactly correct @indraShan. Categories are attached to each issue so you'll have to look through to see which categories exist, then organize the issues into groups based on what you have.

If you're gonna take a shot at this, just mention it here so anyone else who stops by knows it's being worked on.

**Comment by indraShan** [comment]
@nickoneill I will give it a shot.

**Comment by nickoneill** [comment]
Awesome, let me know if you have any questions.

**Comment by nickoneill** [comment]
fixed in #194
