### ISSUE TITLE
Informational screen for people who copy scripts

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#175]
(I recall a bunch of discussion on this previously but I can't find a branch where any work had been done here... correct me if I'm wrong though)

Copying scripts for faxes or emails is never going to be a thing we can prevent but at least we could inform people why they should call instead when they're doing this.

* If a user selects and copies the text in a script, the copy should be successful but we should surface a modal dialog that informs the user that calling is more effective than other methods of communication
* Informational text could be as follows:

#### Emails and faxes take significantly longer to record than phone calls. If the issue is urgent, calling may be your only way to be heard! Still don't want to talk to someone? Leave a voicemail after normal office hours.

**Comment by Abizern** [comment]
This has already been done. However, it only works the first time you try and copy something. After that no alert appears, but noting gets copied. I haven't looked into why this happens yet.

<img width="363" alt="screen shot 2017-10-11 at 22 19 21" src="https://user-images.githubusercontent.com/6902/31467632-8b0a9c04-aed2-11e7-8b20-493dec7fce7e.png">

**Comment by nickoneill** [comment]
Ohhh, I see. Interesting. Thanks for looking in to this.
