### ISSUE TITLE
More issues has no back button on iPad

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#176]
Should be easy to get back to the main list of issues from more issues.

![20170927_132945](https://user-images.githubusercontent.com/49688/30936258-1b088da8-a388-11e7-9377-3e7b7f622079.jpg)

**Comment by indraShan** [comment]
Is anyone working on this? Should I attempt?

**Comment by nickoneill** [comment]
I don't think anyone is working on it. It may be inconsistent, and definitely check on both iOS 10 and 11.

**Comment by mccarron** [comment]
This one is a bit tough, the top bar on the iPad blocks where the Navigation Controller would be (it's not a thing on the iPad split view, but blocks it when I add one). I'm going to try to create a few tweaks to get something like this to work properly and look good. 

![simulator screen shot - ipad air 2 - 2018-01-28 at 22 21 41](https://user-images.githubusercontent.com/45654/35493531-b75f127e-0479-11e8-9fae-855e6c388c7e.png)
