### ISSUE TITLE
Logo in navigation bar doesn't play well with the iPhone X notch

### ISSUE THREAD

**Issue by Abizern** [5calls/ios#180]
Still a couple of weeks left to solve this.

![simulator screen shot - iphone x - 2017-10-07 at 00 09 08](https://user-images.githubusercontent.com/6902/31301792-96bd5514-aaf4-11e7-9cb2-d8ead37d7e41.png)

**Comment by Abizern** [comment]
Who's the lead on design for the mobile apps?

**Comment by subdigital** [comment]
It's been a group effort.  I started the app following the design of the web app. Later started to move more toward more native conventions, after receiving some excellent design feedback from , which has been addressed somewhat, but not entirely.

@ianyh @nickoneill and myself can provide some direction or validation if you have a specific question, otherwise just go for what you think will work well and looks like it belongs on the platform.

**Comment by nickoneill** [comment]
Playing around with some options that would shorten the header for all platforms...

<img width="771" alt="screen shot 2017-10-09 at 5 53 07 pm" src="https://user-images.githubusercontent.com/49688/31364641-067e2eb4-ad1b-11e7-9639-40deda05b549.png">
<img width="757" alt="screen shot 2017-10-09 at 5 53 41 pm" src="https://user-images.githubusercontent.com/49688/31364642-0696436e-ad1b-11e7-9138-b610d8a0d681.png">
<img width="757" alt="screen shot 2017-10-09 at 5 54 21 pm" src="https://user-images.githubusercontent.com/49688/31364643-06af24a6-ad1b-11e7-8aa3-f00e716743dc.png">

Definitely liking the idea of ditching the full logo text for the stars alone. I'm sure some executive somewhere is rolling in their grave "they didn't make the logo bigger..."

**Comment by Abizern** [comment]
FWIW, I like the second header. I think it looks clean and the notification button is at the top right which is more natural for most people.

Maybe to keep to the colour scheme, you could make the top star of the logo red?

**Comment by nickoneill** [comment]
Yeah, the second option feels good too. We've used the stars alone before, I think we can get away with it here without changing the colors.

If notifications here is going to be both local reminders and options for remote, I wonder if it makes more sense to make it a "settings" gear and then drop you into the about controller where notification settings can live alongside about info.

**Comment by Abizern** [comment]
Using a gear might be a better option. Looking at this again, having a rendered bell rather than a line icon (if you know what I mean) seems a bit out of kilter with modern UI.

**Comment by subdigital** [comment]
That rendered bell is an emoji I think, and I don’t think we ever intended to keep it 😜

In fact, now I remember…. I wanted to use something from Parakeet Primaries (I own it), but since this is open source I was cautious. I asked for permission from Louie on twitter, but I don’t think I ever heard back.

**Comment by nickoneill** [comment]
Yeah, I just happened to have an emoji bell in sketch when doodling this. Lemme see if I can find an icon for settings...

**Comment by Abizern** [comment]
I've got one from Glyphish
<img width="96" alt="screen shot 2017-10-11 at 00 09 53" src="https://user-images.githubusercontent.com/6902/31415002-999cc34c-ae18-11e7-8fec-fee36c5e5455.png">

I own it and the licence states: "You're free to use these icons for commercial and non-commercial purposes, for yourself, your company and your clients, and to edit, remix and otherwise modify them without attribution."

**Comment by subdigital** [comment]
I met the glyphish guy at a conference a while back. Pretty sure he’d be thrilled at us using it :)

**Comment by nickoneill** [comment]
![5calls-settings 2x](https://user-images.githubusercontent.com/49688/31415036-bb7003e6-add5-11e7-8f95-e46e18bf25b1.png)
![5callslogo 2x](https://user-images.githubusercontent.com/49688/31415037-bb89806e-add5-11e7-8fa9-992ac887615b.png)

**Comment by nickoneill** [comment]
I'm a bit more fond of the UI8 one posted above (similar "do whatever" license). Does it make sense to have the color baked in or do it in code?

**Comment by ianyh** [comment]
Template images with tint colors is usually better because they support accessibility options for things like color inversion.

**Comment by ianyh** [comment]
Also, I think I have a vector rendering of the stars icon somewhere that I can dig up.

**Comment by nickoneill** [comment]
![5calls-settings 2x](https://user-images.githubusercontent.com/49688/31415138-5e21deac-add6-11e7-9f81-a5275725f6af.png)

**Comment by Abizern** [comment]
If the image is a solid colour, then, as @ianyh says, template image with tint is a better option.

**Comment by nickoneill** [comment]
The egregious stuff is fixed in #197, gonna keep this open for the moment for the alternate headers

**Comment by Abizern** [comment]
👍

-- 
Abizer
