### ISSUE TITLE
Move to UNUserNotification now that UILocalNotification is deprecated

### ISSUE THREAD

**Issue by Abizern** [5calls/ios#183]
Since the base SDK is iOS 10 these warnings are showing up in Xcode. Probably a good idea to move away from the deprecated methods.

**Comment by Abizern** [comment]
It probably makes sense to wait for #172 and #170 before doing this. Not sure.

**Comment by nickoneill** [comment]
Yeah, I'll mess around with #170 this week.

**Comment by Abizern** [comment]
Covered by #240
