### ISSUE TITLE
UITest Failure - Can't find "Defend the Affordable Care Act Static text"

### ISSUE THREAD

**Issue by Abizern** [5calls/ios#185]
the `testTakeAScreenshot()` test is failing because this static test cannot be found.

**Comment by nickoneill** [comment]
This one was pretty solid for a while but now isn't on the list anymore. If it doesn't matter which issue, let's just select #2 on the list. Otherwise maybe we have to start mocking these requests in tests?

**Comment by subdigital** [comment]
Not near a computer but IIRC this was served from a static json file for tests...
