### ISSUE TITLE
Use the native SKStoreProductViewController for when a user manually wants to leave a review.

### ISSUE THREAD

**Issue by Abizern** [5calls/ios#187]
In the About page of the app, one of the options is to leave a review. This creates URL than is opened in Safari.

Another option would be to push an SKStoreProductViewController with the iTunes app id, which would open the view within the app rather than externally to the app.

Just a thought, comments are welcome.

**Comment by nickoneill** [comment]
Yep, there's no benefit to going to the store in Safari. Let's share whatever we can from the native rating work you're doing in #186 for this location too!

**Comment by Abizern** [comment]
IMO there is no overlap. This just needs to push a different view controller. Unfortunately, testing it is a bit difficult as I’m registered with the UK store, so I’ll need someone else to verify my implementation. I’m thinking I’ll just write the new code and add it to my current PR.

**Comment by nickoneill** [comment]
Sure thing, happy to test it out in the US

**Comment by Abizern** [comment]
Okay, I've looked into this a little bit more and my original solution isn't going to work. SKProductViewController isn't supposed to be used for rating apps.

So, I'll use the native request from #186 for this if the device supports it, and fall back to the original method otherwise.

The only worry I have is that as we have no control over whether or not the prompt actually shows following the request it may happen that tapping the cell shows nothing. On the other hand, It's likely that the user is unlikely to tap the button if they have been prompted recently, so it may not be as much of a problem as it appears.
