### ISSUE TITLE
Header alignment for issue list

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#190]
I may have been a bit overzealous with that last storyboard merge...

<img width="396" alt="screen shot 2017-10-10 at 3 45 07 pm" src="https://user-images.githubusercontent.com/49688/31414442-c5ef374a-add2-11e7-9898-ca995ea12ca2.png">

**Comment by Abizern** [comment]
That’s weird, I don’t think I touch the cells. Would you like me to take a look at it?

**Comment by nickoneill** [comment]
Nah, I'll check it out. Just capturing here for clarity.

**Comment by nickoneill** [comment]
Fixed in #191
