### ISSUE TITLE
Switch to System Font instead of Roboto family

### ISSUE THREAD

**Issue by Abizern** [5calls/ios#192]
Should make #144 easier.

**Comment by nickoneill** [comment]
This is done, right @subdigital?

**Comment by subdigital** [comment]
Not sure, will have to grep to verify...

**Comment by Abizern** [comment]
Sorry I've been remiss about this.

I'm having a look at the current master and there are comments that the styles are being set for consistency with the Web - i.e. fonts being condensed and bold. getting rid of Roboto will break this. Just checking that this is still the way you want to go and that a different appearance between the web and the app is acceptable.
