### ISSUE TITLE
Extract strings in preparation for localization

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#20]
Currently the app uses hard-coded strings.  We're prepping to localize everything into some other languages.  The first step is to extract the strings in the app into strings files so we can hand these off to translators.

**Comment by alexanderjrobinson** [comment]
What do you think about using something like R.swift for the localization strings?

**Comment by subdigital** [comment]
Not familiar with it, looking now.

**Comment by subdigital** [comment]
Tracking this in #61
