### ISSUE TITLE
skip issue behaves differently on iOS than elsewhere

### ISSUE THREAD

**Issue by piebob** [5calls/ios#206]
"if I Skip an issue it marks it as Complete, but on the iOS version it does not. Can you please add an iOS preference, or else change the app completely, so that Skip marks an issue as Complete?"

**Comment by mccarron** [comment]
I can do that this weekend if @subdigital and @nickoneill agree.

**Comment by nickoneill** [comment]
People can be somewhat fussy about how this behaves... I'm trying to think about what makes more sense as a default behavior. If we make the change where skip -> completed, people will definitely complain that their method of tracking who they have/havne't called is changed.

I would prefer to leave it as-is and implement the circular contact progress indicator. That way people who only call 2-of-3 (why?) can know they've completed all the calls then intending on making

**Comment by piebob** [comment]
i don't have an opinion of how it should behave--what you suggest is fine by me--but i do think it should behave exactly the same way on every platform.

**Comment by mccarron** [comment]
I agree with keeping it consistent cross platform, maybe in the `circular contact progress indicator` implemented future we can align everything.

**Comment by nickoneill** [comment]
For sure, I envision the same behavior in all places. I added issues specifically for this to ios, android and web. Closing this.
