### ISSUE TITLE
Contact and issue completion circles are not working

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#213]
We opted to keep the local results because they were powering the circles that indicate when both an issue was complete, and when you had called a contact in the contact list.

It looks like something that happened during that transition stopped these circles from indicating progress. @melville maybe you know more about this?

**Comment by melville** [comment]
I took a look at this issue but I don't see a mechanism in `CheckboxView` for indicating partial progress, so I'm not sure how this is supposed to work.  I don't see anything in `IssuesViewController` that's trying to figure out whether there is partial progress when it's setting up its cells either.  It's certainly possible that I'm missing something, but it doesn't look like there is any code that implements this feature at the moment.

**Comment by nickoneill** [comment]
Sorry, I think I confused you with the wrong terminology.

You're correct there's no indication that you've called 1/3 contacts for a particular issue (except for the individual completion checkmarks on each contact). But the issue checkmark should show up when you have made *all the calls*, so people can track which issues they've called and which they have not.

**Comment by melville** [comment]
In that case I'm not able to reproduce the issue.  I am seeing the checkmark next to the issue in the list after I've made all the contacts.  Do you have any steps that will reproduce the problem?  Maybe this only happening under certain circumstances or on certain devices or versions of iOS.

**Comment by nickoneill** [comment]
Nevermind! Works fine, I was just using "unavailable" to test which... naturally doesn't mark them as contacted.
