### ISSUE TITLE
Markdown not parsing in descriptions and scripts

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#214]
I just tested a couple markdown examples in the description and script and it doesn't look like they're parsing correctly to styled text.

Can you take a look @mccarron? Let me know if you need me to add test markdown to an older issue, I removed it from this issue after I tested.

Both of the screens below have text that has `__test markdown__` which should be bold

**Comment by nickoneill** [comment]
![img_3174](https://user-images.githubusercontent.com/49688/41789305-b2eb6700-7603-11e8-8fdb-802273078ec4.PNG)
![img_3175](https://user-images.githubusercontent.com/49688/41789306-b32a4e5c-7603-11e8-932b-9327ae099671.PNG)

**Comment by mccarron** [comment]
Yeah we didn't add Markdown support yet just a pod that adds the ability to parse Markdown. You said the API didn't have Markdown yet so there wasn't anything to do. ;) 

Can we get some Markdown onto a Staging/Test API to build this out?

**Comment by nickoneill** [comment]
I don't have a staging API for the main issues list (it's getting moved to a different server soon that already has a staging API) but I added some test markdown to an issue on the more issues list: "Protect the Right to Fight Workplace Sexual Harassment"

Let me know if that works OK.

**Comment by mccarron** [comment]
Sure that'll work, I'll take a look at hooking this up either tomorrow or Sunday then.

**Comment by nickoneill** [comment]
🏓

**Comment by nickoneill** [comment]
Done!
