### ISSUE TITLE
Increase the contrast of the text on the "Enable Reminder" screen

### ISSUE THREAD

**Issue by foozmeat** [5calls/ios#216]
I find it hard to read on my phone. I think using the regular blue color here would be fine. 

![img_aaca91d653c2-1](https://user-images.githubusercontent.com/419456/43739831-3d744066-997e-11e8-9406-4a81c1630e25.jpeg)

**Comment by subdigital** [comment]
Agree it’s hard to read but we should avoid using blue color for things that aren’t interactive.

**Comment by foozmeat** [comment]
fair enough

**Comment by nickoneill** [comment]
What about good old #000000

**Comment by subdigital** [comment]
I think lower contrast is better, but perhaps not as much as it is now.

**Comment by heathermh** [comment]
Fixed by https://github.com/5calls/ios/pull/374
