### ISSUE TITLE
Funky header on iPhone Plus Sized Screens after Rotation

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#218]
It appears that after a rotation on a Plus sized iPhone screen that uses the Split View Controller the menu bar is not laid out properly. 

![file](https://user-images.githubusercontent.com/49688/44062327-b370efc0-9f10-11e8-8c67-15fe79de8337.jpg)

Original Report:

I know we touched this recently for the iPhone X, but it looks fine on my iPhone 7+ (iOS 12... but I don't think we've messed with the header since I had iOS 11 on it either)

**Comment by mccarron** [comment]
I'll take a look this weekend at this and the two crashes.

**Comment by nickoneill** [comment]
Thanks!

**Comment by mccarron** [comment]
This is reproduced by rotating and un-rotating the device.
