### ISSUE TITLE
Titles are truncated on the more issues page

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#220]
A user reports that her "more issues" page looks like this:

![p8y2aori-2](https://user-images.githubusercontent.com/49688/44286863-6ceda680-a21f-11e8-8efa-632cfabe3da2.jpg)

It doesn't look like this for me on iOS 12. User says iPhone 7+ on 11.4.1

**Comment by mccarron** [comment]
@nickoneill I can't seem to reproduce this. Did they say it shows this every time? If not, can we get reproduction steps if they think they can reproduce it?

**Comment by nickoneill** [comment]
I will check

**Comment by nickoneill** [comment]
They just open the app and go to more issues and this is what they see. I'll check around with a few settings. Maybe font size accessibility?

**Comment by nickoneill** [comment]
Yep, if you turn larger accessibility sizes on (at about 33% and above), you get just one line of truncated title. Looks like we don't honor that setting on the front page list.

Not sure what effort is required for making the cells auto-height to the full text size. If it's excessive, let's disable accessibility sized text on the more issues cells and do a full run through in the next release.
