### ISSUE TITLE
Dynamic height rows seems to cause the issues list to shuffle

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#23]
I noticed that once we supported dynamic height on the issues list, the table reshuffles strangely when scrolling.

Another (probably related) thing is this occasionally causes our labels to no longer wrap & cause their cell to increase in height, instead reverting to truncating with ellipses ('...').

**Comment by subdigital** [comment]
@bjtitus is looking into this

**Comment by mccarron** [comment]
Likely what I see doing this as well

![simulator screen shot feb 4 2017 7 57 21 pm](https://cloud.githubusercontent.com/assets/45654/22623098/362d5d34-eb14-11e6-869d-4ce202845f77.png)

**Comment by bjtitus** [comment]
@mccarron @subdigital See if that PR fixes your issue. The unnecessary reload call is what was triggering this for me. Let me know if you're seeing it in other cases with that call removed.
