### ISSUE TITLE
Replace Fabric with something else for Crash + Analytics

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#239]
Things that are important in this service:

* iOS and Android support
* Analytics for users over time
* Crash reporting
* Logins for team members (so @subdigital, @mccarron, @dektar and others can see this data without sharing logins)

Nice-to-have:

* Push notifications (we use onesignal now, but would love to have one less service
* Free is nice, but not required (we have credits on Google and AWS, so those are effectively free)
* Testing? We don't do a lot of this now, could be nice to have.
* Web analytics (I would love to unify analytics for everything in one place)

Things we don't care about:

* User auth / login services (already have it through auth0, happy with it)
* Ad platforms
* Databases
* Hosting

**Comment by subdigital** [comment]
I’d like to recommend considering http://appcenter.ms <http://appcenter.ms/>. I’ve had a positive experience with it on a couple of projects. Bonus: their SDK is open source, so you know what they’re doing by embedding it in your app.

**Comment by nickoneill** [comment]
Nice, I haven't seen this in action yet. I'll check it out, not contribute to google knowing everything is a bonus.

**Comment by nickoneill** [comment]
I'm gonna go with appcenter for this, I've heard a couple other good reviews as well!

**Comment by nickoneill** [comment]
Fixed in 4698bf16d3e0ba15a6727e062cb8577cc66797cb
