### ISSUE TITLE
Cells don't resize correctly after rotation

### ISSUE THREAD

**Issue by Abizern** [5calls/ios#241]
When rotating from Portrait -> Landscape -> Portrait the cells do not resize correctly. There is too much vertical space.

Scrolled cells do resize though.

![1 - initial portrait](https://user-images.githubusercontent.com/6902/45927575-2893ab80-bf2d-11e8-9139-4585e35a4a64.png)

![2 - rotated to landscape](https://user-images.githubusercontent.com/6902/45927577-2c273280-bf2d-11e8-97a3-1a3683b46599.png)

![3 - rotated back to portrait](https://user-images.githubusercontent.com/6902/45927578-2df0f600-bf2d-11e8-9d87-77b7b4e05fe1.png)

**Comment by nickoneill** [comment]
Good catch @Abizern! I'm a never-rotate guy and I always forget to test this.

**Comment by subdigital** [comment]
I’d vote for disabling rotation myself, but since we have the iPad app I’m not sure that’s a good idea.

**Comment by Abizern** [comment]
I think it's fixable, myself.

**Comment by Abizern** [comment]
I've spent a bit of time on this over the weekend and there is something definitely weird going on. Even the old standby of using a stack view doesn't work - even though it works fine in a test app. I'll have to come back to it at a later time.

**Comment by nickoneill** [comment]
thanks for taking a look @Abizern. It's a little funky but doesn't block folks from getting to where they're going so not critical for now.

**Comment by fingersakimbo** [comment]
I just tried on iOS 11, Xcode 9.4.1 ... still not seeing it.  I don't think it's a problem anymore.  Shame, because I thought it would be a good starter task for me.

**Comment by nickoneill** [comment]
I agree, let's wait to see if there's a specific repro case that we can fix if it's not straightforward.

What do you think about looking into #207 @fingersakimbo? There's some work that was done a while back in #196 that did this (see the screenshots), but it has a bunch of other work in it that never made it to mergability.

**Comment by fingersakimbo** [comment]
Sure, I'll take a look.

**Comment by nickoneill** [comment]
All set @fingersakimbo, thanks for your help getting those progress views pulled in.

#250 is new as well if you want to pick that up, just leave a comment.

**Comment by Abizern** [comment]
Re - reproducibility - The simulator shows it up. Maybe it's a bug with that? Maybe that's why I couldn't fix it :(

**Comment by nickoneill** [comment]
I'm going to bump this out of 1.5.3 since it seems hard to reproduce on a real device

**Comment by Abizern** [comment]
I'm going to close it, unless I can see it on a device again.
