### ISSUE TITLE
Users seeing local results / session refresh problem

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#247]
Still seeing some user reports of server stats not showing consistently, even though I can't reproduce the problem on my device. The reports match with 401 errors (unauthorized) on the server, so I'm guessing it has something to do with the re-auth cycle. Keep in mind 401 errors aren't sent back on every request (the issues request doesn't require auth, so it doesn't check for it) so the first time these users could see a 401 is when they open the Impact screen.

So: if a user opens the impact screen and gets a 401, does the original request retry again after auth has been renewed? It doesn't look like it from the logs, I see a 401 and then no other request to the user stats endpoint unless I ask the user to go back in and look at the page again.

Ideas? @subdigital?

**Comment by iainsmith** [comment]
Does the app make strictly one api request at a time or do parallel calls happen?

**Comment by nickoneill** [comment]
Currently one at a time - this one should always be a serial request, in `FetchStatsOperation` I think.

**Comment by nickoneill** [comment]
I think this was a auth refresh timing mismatch, fixed now
