### ISSUE TITLE
Main.storyboard is reporting several autolayout/constraint issues

### ISSUE THREAD

**Issue by fingersakimbo** [5calls/ios#249]

**Comment by fingersakimbo** [comment]
<img width="268" alt="screen shot 2018-10-25 at 9 58 54 pm" src="https://user-images.githubusercontent.com/26525347/47542045-34162180-d8a1-11e8-9548-5f386a8e5ac8.png">

I'm happy to tackle these, but I don't want to cause a merge conflict with the PR for circular progress.

**Comment by nickoneill** [comment]
That would be great - will review the progress circles tomorrow so we can get it merged in.

**Comment by fingersakimbo** [comment]
I haven't forgotten about this. It's just more complicated than it seems. IB really, really, really hates the tableHeader on MyImpactViewController, and the quick fixes I tried didn't work. So, I'm going to roll up my sleeves and make some components.

**Comment by nickoneill** [comment]
Thanks @fingersakimbo! Appreciate the devotion to this issue
