### ISSUE TITLE
Users can't say "No Thanks" to notifications

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#250]
After a user completes a set of calls for the first time, we ask them if they want to get notifications about new issues. The choices are:

1. All Issues
2. Important Issues
3. No thanks

Only 1 and 2 launch the notification prompt, and saying "No thanks" doesn't set any value that we can check in the future so we ask *every single time* when the user doesn't want notifications.

Lets be less annoying and only ask once every month if a user says "No thanks".

**Comment by fingersakimbo** [comment]
I'll take this one.

**Comment by nickoneill** [comment]
Closed with #252
