### ISSUE TITLE
On plus-sized devices, left pane in landscape mode has no top bar

### ISSUE THREAD

**Issue by fingersakimbo** [5calls/ios#251]
The table view shows through where the navbar should be.

![simulator screen shot - iphone xr - 2018-10-27 at 15 25 55](https://user-images.githubusercontent.com/26525347/47609016-e57d9a00-d9fc-11e8-81e9-895c289d3b4b.png)

**Comment by nickoneill** [comment]
We talked a bit about this effect at the time we were doing iPhone X updates, but deferred actually coming up with what the real solution was.

Can we treat the table header the same way we're treating the location header on the other side? As long as that text doesn't get so large that it extends into the top left corner we should be good to not block any content.

**Comment by nickoneill** [comment]
fixed in swiftui version
