### ISSUE TITLE
Experiment with mixpanel for user behavior analytics

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#256]
As part of #239, we're replacing fabric with something else for mobile analytics. Before we go full-on tracking everything in the app, I'd like to see how it behaves tracking data on multiple platforms.

I've already integrated mixpanel with the website. I'm going to do a quick test integration for iOS on 1.5.3 so we can see if both sets of data can live nicely along side one another.

**Comment by nickoneill** [comment]
we experimented, it's garbage

**Comment by Abizern** [comment]
There are still a couple of calls that use it, and the Pod. Can they be removed?

**Comment by nickoneill** [comment]
Yep, I'm still looking for a good way to get insights into how many users we have and how they use the app, but we can remove mixpanel because I'm not using it at all right now.
