### ISSUE TITLE
Include screenshots for iPhone Xs Max and new iPad 12.9" sizes

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#259]
These are app-store optional, but we should add them to the screenshot flow for next release.

**Comment by mccarron** [comment]
👍 will get those added.

**Comment by nickoneill** [comment]
Thanks! This'll be for the next big release, probably early next year

**Comment by nickoneill** [comment]
These are required now:

> Starting March 27, 2019, all app submissions for iPhone or iPad, including universal apps, will require screenshots for iPhone XS Max or the 12.9-inch iPad Pro (3rd generation).

**Comment by mccarron** [comment]
I'll try to get these added this week sometime during session downtime, unless someone can get it to before me.

**Comment by mccarron** [comment]
Updated Fastlane to make this work and also sent @nickoneill the screenshots but they are also in the Repo.
