### ISSUE TITLE
Login flow cancel causes a crash

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#262]
My Impact -> Sign in -> "5 Calls would like to use auth0.com to log in" -> Click cancel -> crash

In bugsnag: https://app.bugsnag.com/5-calls-civic-action/5-calls-ios/errors/5c152d71027305001a66bae4

**Comment by Abizern** [comment]
I think #261 deals with this one.

**Comment by nickoneill** [comment]
Fixed in #261
