### ISSUE TITLE
Framework not found Pods_NotificationsService

### ISSUE THREAD

**Issue by SakDangler** [5calls/ios#269]
Upon cloning down, there is a build error related to the linker on the NotificationService.

Build target NotificationsService of project FiveCalls with configuration Debug
ld: framework not found Pods_NotificationsService
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nickoneill** [comment]
Xcode version?

**Comment by SakDangler** [comment]
Version 11.2 (11B52)

**Comment by nickoneill** [comment]
Seems fine in xcode 11 - did you `pod install` and then open the workspace file rather than the project?
