### ISSUE TITLE
Replace deprecated usage of UIWebView

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#299]
During our most recent submission:

> ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by mccarron** [comment]
Was this the first warning we got of this? I've been getting them since the iOS 13 betas, did we add a new third party library?

**Comment by nickoneill** [comment]
I don't think it was the first, just the first time I captured them in issues.
