### ISSUE TITLE
iOS14: App Clip

### ISSUE THREAD

**Issue by Abizern** [5calls/ios#313]
An app clip to support a "QR" code that could be added to emails, flyers, posters etc regarding an issue.

The app clip would support loading the Issue detail, getting the general location and providing the contact details of relevant representatives.

https://developer.apple.com/app-clips/

**Comment by subdigital** [comment]
That’s a great idea. 👍🏼

**Comment by nickoneill** [comment]
This is an awesome idea, it would be amazing to do stickers on high-profile topics that we can send out to folks

**Comment by nickoneill** [comment]
Closing as our app has significantly reduced it's size, negating the need for an app clip
