### ISSUE TITLE
SwiftUI design / 2.0 release

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#331]
App needs a design refresh, both because it's been 6 years since the initial work was done and because SwiftUI makes it a hell of a lot easier to build new stuff.

Started on quite a bit of it here: https://github.com/5calls/ios/pull/329
I would like to not keep the whole redesign in a single PR but unless there are other changes hitting main it doesn't really matter. 

**Tracking some (not at all comprehensive) todos:**
- [x] Loading issues, contacts
- [x] Send outcomes back to server
- [x] Setting location, persisting location
- [x] Dashboard / Main issues view
- [x] #352
- [x] Issue detail view
- [x] Issue contact detail view (i.e. script and phone numbers for an issue + specific contact)
- [x] Done page design
- [x] About view
- [x] Reminders view
- [x] My Impact view
- [x] #349
- [x] #395
- [x] #365
- [x] Modern welcome screen @heathermh
- [x] #363
- [x] #366
- [x] #377
- [x] #379
- [x] #400
- [x] #380
- [x] #388
- [x] #387
- [x] #384
- [x] #409
- [x] for contact's list of phone numbers, can we keep the phone symbol showing at larger dynamic type settings? https://github.com/5calls/ios/pull/427
- [x] check if IssueContactDetail needs to check for reduce motion / limit animations (I don't think it does)

**Bugs**
- [x] Welcome screen doesn't show paging pips
- [x] #362
- [x] Placeholder contact circles are not aligned correctly
- [x] #368
- [x] If we haven't loaded a contact for an area, clicking "see your script" crashes (we should probably show an error "can't find any contacts for this issue in your location, try a different location")
- [x] ~~iPad: tapping twice on "Detect my location" complains about leaked continuations (my iPad takes a long time to get a location? needs a disabled state)~~ seems fine now
- [x] iPad: changing your location should reload the issue detail to reflect new contacts
- [x] #382
- [x] Placeholders show 2 for House, 1 for Senate, should be reversed
- [x] ~~Location header on iPad cannot be tapped~~ dunno, this seems fine now
- [x] #391
- [x] #401
- [x] #393
- [x] #413
- [x] #426
- [x] #428 
- [x] https://github.com/5calls/ios/issues/430

**Cleanup tasks for after this is done and ready for prod:**
- [x] Move plausible tracking to the new views
- [x] #370
- [x] Remove unneeded 3p stuff: firebase, down, Promises

**Comment by heathermh** [comment]
Modern welcome screen suggestion. What do you think? This should easily support dark mode and dynamic type.

<img width="427" alt="image" src="https://github.com/5calls/ios/assets/1638675/504a9ab0-f915-4c93-8a75-ede39253c363">
<img width="685" alt="image" src="https://github.com/5calls/ios/assets/1638675/ac534b30-b8a2-4051-ab34-0abe78151fff">

**Comment by nickoneill** [comment]
This looks great @heathermh, open a PR and I can add some specific feedback.

**Comment by nickoneill** [comment]
done
