### ISSUE TITLE
Re-integrate an open source acknowledgements section

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#333]
Currently broken and being removed (#332), we should still list the open source contributions though. Since we're reworking a lot of the deps for the SwiftUI design (#331), let's revisit for that project rather than try to list the current UIKit deps that will mostly be removed.

**Comment by cselin** [comment]
@nickoneill thoughts about using [this](https://github.com/vtourraine/AcknowList)? It seems to be pretty up-to-date and has dozens of forks and hundreds of stars.
