### ISSUE TITLE
build fails / missing build input file GoogleService-Info.plist

### ISSUE THREAD

**Issue by heathermh** [5calls/ios#347]
I'm attempting to build the project for the first time. Getting error "build input file cannot be found... GoogleService-Info.plist" while building target FiveCalls.

I see that this file is loaded as a resource file in R.generated.swift. The other files in that struct are part of the repo (ex: FiveCalls/FiveCalls/about-whoweare.html). 

Would appreciate if someone could add the file or help me out if I've missed something. Thanks!

**Comment by nickoneill** [comment]
Hi @heathermh, pop an email to nick@5calls.org and I'll get you set up!

**Comment by nickoneill** [comment]
resolved via email

**Comment by cselin** [comment]
@nickoneill it might be worth adding something about this to the readme since I struggled with this when I started contributing as well.
