### ISSUE TITLE
App Store Metadata

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#36]
Need:

- [x] keywords
- [x] description
- [x] app store screenshots

**Comment by subdigital** [comment]
Just riffing off the website, how's this?

> MAKE YOUR VOICE HEARD
> 
> Turn your passive participation into active resistance. Facebook likes and Twitter retweets can’t create the change you want to see. Calling your Government on the phone can.
> 
> Spend 5 minutes, make 5 calls.
> 
> Calling is the most effective way to influence your representative. Read more about why calling works.
> 
> 5 Calls:
> 
> - Provides phone numbers and scripts so calling is quick and easy
> 
> - A background on why each issue is important so you can  judge how important each one is to you
> 
> - Uses your location to find your local representatives so your calls have more impact
> 
> - Keeps track of who you've called about each issue so you can make your way down the list
> 
> TOGETHER WE’VE MADE over 384,000 CALLS!

**Comment by alexanderjrobinson** [comment]
Here is the Play Store entry for reference. https://play.google.com/store/apps/details?id=org.a5calls.android.a5calls
