### ISSUE TITLE
Accessibility pass

### ISSUE THREAD

**Issue by nickoneill** [5calls/ios#365]

**Comment by heathermh** [comment]
Reminders: https://github.com/5calls/ios/pull/374

**Comment by heathermh** [comment]
My impact: https://github.com/5calls/ios/pull/375

**Comment by heathermh** [comment]
About: https://github.com/5calls/ios/pull/376

**Comment by heathermh** [comment]
@nickoneill and @cselin I'm testing out possibly combining ContactListItemCompact and ContactListItem. The more I look at them, the more I realize they're super similar and it's better to handle their accessibility all at once. Plus, hopefully we can get some design benefits from combining them. One particular bit is the background color for each contact person we list. Please check out the screen grabs below, and let me know if you like them with the grey background, or without the grey background? Always open to other thoughts, too.

These are the IssueContactDetail view and it uses the regular size ContactListItem. I'll include light/dark with and without the grey background.
<img width="214" alt="IssueContactGrayLight" src="https://github.com/5calls/ios/assets/1638675/13df9e96-9f58-41b7-8906-37db3a8a2b95"><img width="214" alt="IssueContactNoGrayLight" src="https://github.com/5calls/ios/assets/1638675/71c95c24-ed3a-4e87-b3f5-1f421863ec3d">
<img width="214" alt="IssueContactGrayDark" src="https://github.com/5calls/ios/assets/1638675/aea63180-f22c-45c9-9b8a-6ca4e599f8cc"><img width="214" alt="IssueContactNoGrayDark" src="https://github.com/5calls/ios/assets/1638675/bc872c85-cf46-4ee1-85a5-550523ca6d4d">

These are the IssueDone view that uses the compact size, light/dark with and without the grey background.
<img width="214" alt="DoneGrayLight" src="https://github.com/5calls/ios/assets/1638675/1cee6c06-1623-475c-84db-dc95f7dcbdaa"><img width="214" alt="DoneNoGrayLight" src="https://github.com/5calls/ios/assets/1638675/37673e53-2ed7-4e0d-8a05-282180cda9d4">
<img width="214" alt="DoneGrayDark" src="https://github.com/5calls/ios/assets/1638675/f6b01f52-bb47-46be-91ed-4e5f44cfabfa"><img width="214" alt="DoneNoGrayDark" src="https://github.com/5calls/ios/assets/1638675/8629eb21-b1ae-44ee-9ca6-4f9a1d0f7576">

**Comment by nickoneill** [comment]
@heathermh let's do without as the default. We can add a background when calling ContactListItem like in IssueContactDetail where I think it looks better but leave it out on IssueDone where it's not needed.

**Comment by nickoneill** [comment]
Do you know when we'll see the next iteration of these improvements @heathermh?

**Comment by heathermh** [comment]
@nickoneill I'm currently focusing on getting report(outcome) in OutcomesView to work for VO users. Have a working theory to try, so may have an update this week/weekend/early next week.

**Comment by heathermh** [comment]
Dashboard, etc: https://github.com/5calls/ios/pull/419
