### ISSUE TITLE
Shorten text that shows after user taps "See your script" button

### ISSUE THREAD

**Issue by heathermh** [5calls/ios#390]
After user taps "See your script", they get a screen for each senator/rep they should contact. There are two versions of the script shown on every screen - can we make it only one that's specific to the rep or senator that they're currently contacting? This would shorten the text, which is especially good for folks using larger text or VoiceOver / other accessibility features.

**Comment by heathermh** [comment]
![Uploading IMG_6781.jpeg…]()

**Comment by nickoneill** [comment]
Good call! We have some script replacements in the current app that we need to port over for names, cities, rep names (created #391), but we've never settled on a format for splitting scripts between house and senate, I think this format works though!

After we do #391, let's expand it to cover this case: `WHEN CALLING SENATE` should include the following paragraph and exclude any other `WHEN CALLING X` paragraphs, removing the `WHEN CALLING SENATE` header entirely. And the opposite for the House.

**Comment by cselin** [comment]
This should be (marginally) easier after we migrate to Swift Regex: https://github.com/5calls/ios/pull/402
