### ISSUE TITLE
Local weekday reminder to make your 5 calls

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#40]
- toggle from welcome screen and settings menu
- schedules local notification for weekdays at a specified time
- on launch schedule the next one if needed

**Comment by chrisbrandow** [comment]
Not entirely clear where it is launching from. I don't see the settings menu. Assuming it's not there yet.

**Comment by subdigital** [comment]
There’s an “About” screen in the footer, it can go in there.  Maybe we need to rename the button, open to suggestions. (Right now “Settings" feels inappropriate because it’s all informational)

**Comment by bengottlieb** [comment]
Is this something that needs to be added? I don't see any code in there for local notifications. Should we add the "feature" tag?

**Comment by subdigital** [comment]
Yes, but I believe @chrisbrandow is working on this already.

**Comment by chrisbrandow** [comment]
sorry for delay. got held up with a few things.
