### ISSUE TITLE
Issues aren't refreshed after initial location detection

### ISSUE THREAD

**Issue by cselin** [5calls/ios#426]
While screen recording for https://github.com/5calls/ios/pull/421 I noticed that the issues weren't loaded after I loaded my location for the first time.

**Comment by nickoneill** [comment]
I'm not sure how you got into this state that you show in the video. Issues are independent of location so it should load the list of issues when the app is launched even if you don't have a location yet, and it doesn't need to reload the issues list when a location is picked.

I tried turning location permission to "never" and relaunching the app like in the screenshare but I couldn't get the issues to fail to load.

If you can't repro I would chalk this up to a transient network problem, I haven't seen anything similar in testing.

**Comment by cselin** [comment]
Can't repro, but found another issue while trying: https://github.com/5calls/ios/issues/430
