### ISSUE TITLE
When calling a contact, VO announces the wrong phone number

### ISSUE THREAD

**Issue by heathermh** [5calls/ios#428]
See video (with sound on). With VO on, if you tap to call a contact (main number or other office numbers), VO announces another number instead of reading the alert for a phone call. (In this case, it seems to be the Portland number for one of my senators, but I'm not sure if that's some sort of default or not). I see that the VO focus box moves over to the area where we're confirming when we copy a number, too. A user with very little to no vision would not be able to see this and would likely lose track of their place in the app.

It shouldn't say this part out loud and should go to the alert at the bottom of the screen to confirm the phone call.

https://github.com/5calls/ios/assets/1638675/53a5a0af-c968-4103-9bc0-94f6382c8377

**Comment by nickoneill** [comment]
I don't see this same effect on the current TestFlight build, it correctly reads the call popup when tapping on a DC or local number.

Can you confirm what branch this is on?

**Comment by cselin** [comment]
Hmm, I'm not seeing this on iPhone 15 iOS 17.2.1. The VO focus on the left should only be happening after a copy and should ready out "Copied phone number" not the actual number. I will say I ran into some race conditions when working on this so it's possible it doesn't work across the board.

**Comment by heathermh** [comment]
Tested again after merging the dashboard accessibility branch and it's announcing correctly for me (iPhone 12 Pro on iOS 17.2.1).
