### ISSUE TITLE
contact's phone number menu not working on iOS 16.x

### ISSUE THREAD

**Issue by heathermh** [5calls/ios#429]
When I tap the menu to see additional office phone numbers for a contact, the menu comes up blank. This only seems to happen on hardware. I'm testing with iPad 6th gen on iPadOS 16.2. The behavior in simulator is different, and also different from within Xcode.

**Comment by nickoneill** [comment]
I don't have a hardware iPad on 16.2, but fwiw the copy menu works fine on a 17.x iPad.

**Comment by heathermh** [comment]
@nickoneill Confirmed it's fine with an iOS update. I'm OK with letting it go if you are.

**Comment by nickoneill** [comment]
Yep, shouldn't be a blocker for right now. Let's keep the issue around for fixing in a future release

**Comment by nickoneill** [comment]
A user reported this on an iPhone 12 with iOS 16.3.1

**Comment by cselin** [comment]
Not seeing it with iPad (simulator) on 16.4. I'm downloading 16.2 for iPhone 12 sim, but it looks like 16.3 isn't available. Will see if I can repro and fix.

**Comment by nickoneill** [comment]
The user reported it with CA senators which work fine for me in a 16.4 sim for iPhone 12, I can pick up a refurb iPhone 8 somewhere if we really can't get it to appear in the sims.

**Comment by cselin** [comment]
I am seeing an issue on the iPhone 12 simulator in 16.2 although not sure if it's the same. Tapping the "..." doesn't appear to do anything so I can get going on a fix for that and see if they menu renders correctly. I also noticed the welcome screen is broken, which I wrote up separately here: https://github.com/5calls/ios/issues/443

**Comment by cselin** [comment]
I'm having a hard time debugging on older OS's, breakpoints aren't getting hit, etc. We *could* build out an alternative UX for 16.3 and under, but I'm wondering how large that user base is and whether it is worth special casing, especially because 2.0 only works on 16.0+ anyway.

**Comment by cselin** [comment]
I noticed a few people mentioning this in App Store reviews so I found a [fix](https://github.com/5calls/ios/pull/446).
