### ISSUE TITLE
ben@scheirman.com on build #26: Test feedback

### ISSUE THREAD

**Issue by alexanderjrobinson** [5calls/ios#46]
Feedback from ben@scheirman.com : Test feedback

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5897bfe9e9a832010023be69/5899e340796da601008f544f/43bc4e66-099f-4a4a-90e4-c0188a512578.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Feb 08 2017 01:11:17 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>4</td></tr><tr><td>App uptime</td><td>17.77419</td></tr><tr><td>Build</td><td>26</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>iBen</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>86% Unplugged</td></tr><tr><td>Memory free</td><td>182 MB / 1823 MB</td></tr><tr><td>Disk free</td><td>18743 MB / 116205 MB</td></tr><tr><td>Network IP</td><td>192.168.1.71</td></tr></table>

 [Link to buddybuild feedback from build 26](https://dashboard.buddybuild.com/apps/5897bfe9e9a832010023be69/feedback?fid=589a70354909110100c8cb2b&bnum=26)

**Comment by mccarron** [comment]
NEVER WILL FIX
