### ISSUE TITLE
Show Checkmark On Call Script Screen 

### ISSUE THREAD

**Issue by mccarron** [5calls/ios#47]
There is no indicator on that screen to show if you've contacted that contact or not.

One suggestion is a `CheckboxView` in a titleView along with `Contact X of Y`.

**Comment by bengottlieb** [comment]
would we want to have some sort of on-device storage in that case, so we can keep track of these calls?

**Comment by mccarron** [comment]
@bengottlieb We do already, we're storing call data with Pantry using the class ContactLogs to log when they tap a call outcome by issue ID and contact ID. ContactLog has a helper `hasContacted`

You can see it used on the main screen: 
https://github.com/5calls/ios/blob/master/FiveCalls/FiveCalls/IssuesViewController.swift#L109

**Comment by bengottlieb** [comment]
Cool, didn't realize that's what Pantry was. Added PR #69 to address this, but uncovered another issue
