### ISSUE TITLE
Smaller Screen Issues

### ISSUE THREAD

**Issue by mccarron** [5calls/ios#55]
* Welcome Screens don't fully fit on an iPhone 4S and SE
* Location Screen doesn't fit an iPhone 4S

![simulator screen shot feb 10 2017 9 14 44 am](https://cloud.githubusercontent.com/assets/45654/22832268/007e45a0-ef73-11e6-8c0b-31fbe0de5a39.png)
![simulator screen shot feb 10 2017 9 12 01 am](https://cloud.githubusercontent.com/assets/45654/22832269/008573ca-ef73-11e6-9720-ef1e538c5b3d.png)
![pasted image at 2017_02_09 10_37 pm](https://cloud.githubusercontent.com/assets/45654/22832912/7f7ec9d6-ef75-11e6-80ef-dc2b09894159.png)

**Comment by subdigital** [comment]
That's frustrating, because it works fine in the simulator:

![iphonese-1-welcome2-3fd692916c8bc2d663ec46d93ca34042](https://cloud.githubusercontent.com/assets/59140/22833107/4d40cee6-ef76-11e6-8c79-c5483f7b4214.png)

**Comment by facto** [comment]
Seeing this as well on iPhone 5S. Thanks again for this app!

**Comment by mccarron** [comment]
@subdigital It is cut off in your photo actually, I have fixed a few of it in the Sim tho. Testing on 4S now which is the smallest iOS 9 supports.

**Comment by subdigital** [comment]
![](http://media3.giphy.com/media/6OWIl75ibpuFO/giphy.gif)

**Comment by subdigital** [comment]
resolved by #62
