### ISSUE TITLE
ben@scheirman.com on build #108: When leaving call feedback on iPad, it's not possible to…

### ISSUE THREAD

**Issue by alexanderjrobinson** [5calls/ios#86]
Feedback from ben@scheirman.com : When leaving call feedback on iPad, it's not possible to navigate back to the issue detail (in order to choose a different candidate. Also, when you finish making your calls, the issue list isn't updated to reflect the check mark.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5897bfe9e9a832010023be69/58aa48aff70cb601008fd31d/78670666-2e80-4748-b25b-0960bfdc9126.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Feb 20 2017 02:09:09 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.1</td></tr><tr><td>CFBundleVersion</td><td>11</td></tr><tr><td>App uptime</td><td>142.9053</td></tr><tr><td>Build</td><td>108</td></tr><tr><td>Device type</td><td>iPad Air 2</td></tr><tr><td>Device name</td><td>Ben’s iPad</td></tr><tr><td>Screen size</td><td>1024</td></tr><tr><td>Screen size</td><td>1024px by 768px</td></tr><tr><td>Battery</td><td>54% Unplugged</td></tr><tr><td>Memory free</td><td>44 MB / 1588 MB</td></tr><tr><td>Disk free</td><td>9344 MB / 116397 MB</td></tr><tr><td>Network IP</td><td>192.168.1.78</td></tr></table>

 [Link to buddybuild feedback from build 108](https://dashboard.buddybuild.com/apps/5897bfe9e9a832010023be69/feedback?fid=58aa4fc5985c430100c24445&bnum=108)

**Comment by bengottlieb** [comment]
Yeah, I wasn't sure how we wanted to handle this. I can add a fake back button to the 'navigation bar'-like image at the top, but if we maintain the full-screen image header, we don't want to use a traditional navigation style.

**Comment by bengottlieb** [comment]
okay, added a Back button next to the Share button.

**Comment by subdigital** [comment]
working in #93
