### ISSUE TITLE
ben@scheirman.com on build #108: This button doesn't feel like a button (no tint color, no…

### ISSUE THREAD

**Issue by alexanderjrobinson** [5calls/ios#89]
Feedback from ben@scheirman.com : This button doesn't feel like a button (no tint color, no change in color when tapped)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5897bfe9e9a832010023be69/58aa48aff70cb601008fd31d/b77b4661-0073-4b4b-8cec-c3b8b5a7a5d0.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Feb 20 2017 02:34:38 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.1</td></tr><tr><td>CFBundleVersion</td><td>11</td></tr><tr><td>App uptime</td><td>1671.638</td></tr><tr><td>Build</td><td>108</td></tr><tr><td>Device type</td><td>iPad Air 2</td></tr><tr><td>Device name</td><td>Ben’s iPad</td></tr><tr><td>Screen size</td><td>1024</td></tr><tr><td>Screen size</td><td>1024px by 768px</td></tr><tr><td>Battery</td><td>49% Unplugged</td></tr><tr><td>Memory free</td><td>55 MB / 1558 MB</td></tr><tr><td>Disk free</td><td>9338 MB / 116397 MB</td></tr><tr><td>Network IP</td><td>192.168.1.78</td></tr></table>

 [Link to buddybuild feedback from build 108](https://dashboard.buddybuild.com/apps/5897bfe9e9a832010023be69/feedback?fid=58aa55be3e1c7d010039642f&bnum=108)

**Comment by bengottlieb** [comment]
added a tint and shows-touch-on-highlight.

**Comment by subdigital** [comment]
Part of #93
