### ISSUE TITLE
Messaging for first call

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#90]
I'd like to add a one-time alert when the user calls to give them some quick instructions about the need to double-tap & come back so they can read the script.

First time user calls, present an alert:

> We're about to place the call. When it starts dialing, turn on Speaker phone, then double tap the home button come back to this app so you can read the script.
>
> **OK, Got it** | Cancel

When we press this button:

- Save an entry in user defaults so we know not to present this alert again
- Call the system dialer

**Comment by nickoneill** [comment]
👍 Great idea!

**Comment by justin** [comment]
I'll tackle this to help the project if no one else has.

**Comment by subdigital** [comment]
Nope, this one’s open for the taking.

**Comment by subdigital** [comment]
Heads up, @tomburns is going to snag this feature.
