### ISSUE TITLE
No way to "uncheck" a call

### ISSUE THREAD

**Issue by armadsen** [5calls/ios#95]
If I mistakenly indicate that I've made contact with a rep, there doesn't appear to be a way to undo that. It's not a huge deal, but for keeping track of issues and calls, it would be nice to be able to fix mistakes.

**Comment by bengottlieb** [comment]
Does the API support this? Would we want to send a message to the server removing the call?

**Comment by subdigital** [comment]
API does not support this, but we could locally.  I think the occasional extra stat isn't going to hurt the numbers that much.

**Comment by subdigital** [comment]
Going to close this as I think addressing #96 resolves the main reason we might need this.
