### ISSUE TITLE
Marking rep as unavailable should not count as complete

### ISSUE THREAD

**Issue by armadsen** [5calls/ios#96]
Right now, if I mark a contact as "unavailable" it counts the same as making contact (green checkmark and all). It seems more useful for it to either show as uncontacted or yellow, or somesuch. That way, I can remember to come back to that contact later. e.g. tonight I called my rep and their voice mailbox was full. I'll try again tomorrow, but 5Calls won't remind me that I need to do that.

**Comment by subdigital** [comment]
Good point. It should definitely move you to the next contact (if there is one), but not mark it as complete. Thanks for reporting this.

**Comment by bengottlieb** [comment]
I put up a PR to treat these as 'completed', but then clear them the next 'day'.
